import 'package:flutter/material.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedGroup20Widget1.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/sigmakediapp/generatedhubwidget/generated/GeneratedGroup46Widget.dart';

/* Frame Hub
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHubWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 263.0,
      height: 824.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(19.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(19.0),
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 261.0,
              height: 65.0,
              child: GeneratedGroup46Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 70.0,
              right: null,
              bottom: null,
              width: 263.0,
              height: 5.0,
              child: GeneratedLine10Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 75.0,
              right: null,
              bottom: null,
              width: 188.0,
              height: 52.0,
              child: GeneratedGroup47Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 132.0,
              right: null,
              bottom: null,
              width: 263.0,
              height: 5.0,
              child: GeneratedLine8Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 137.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 58.0,
              child: GeneratedGroup21Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 200.0,
              right: null,
              bottom: null,
              width: 263.0,
              height: 5.0,
              child: GeneratedLine7Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 205.0,
              right: null,
              bottom: null,
              width: 153.0,
              height: 53.0,
              child: GeneratedGroup19Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 263.0,
              right: null,
              bottom: null,
              width: 263.0,
              height: 5.0,
              child: GeneratedLine6Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 268.0,
              right: null,
              bottom: null,
              width: 169.0,
              height: 58.0,
              child: GeneratedGroup20Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 331.0,
              right: null,
              bottom: null,
              width: 263.0,
              height: 5.0,
              child: GeneratedLine9Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 336.0,
              right: null,
              bottom: null,
              width: 175.0,
              height: 58.0,
              child: GeneratedGroup20Widget1(),
            )
          ]),
    ));
  }
}
