import 'package:flutter/material.dart';
import 'package:flutterapp/sigmakediapp/generatedmessagepagewidget/generated/GeneratedLine13Widget1.dart';
import 'package:flutterapp/sigmakediapp/generatedmessagepagewidget/generated/GeneratedFrame33Widget.dart';

/* Frame Message Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessagePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 361.0,
        height: 801.3441162109375,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.00140380859375,
                height: 5.0,
                child: GeneratedLine13Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 1.0000001192092896,
                right: null,
                bottom: null,
                width: 361.0,
                height: 800.3441162109375,
                child: GeneratedFrame33Widget(),
              )
            ]),
      ),
    ));
  }
}
