import 'package:flutter/material.dart';
import 'package:flutterapp/sigmakediapp/generatedframe43widget1/generated/GeneratedlanlarmWidget.dart';
import 'package:flutterapp/sigmakediapp/generatedframe43widget1/generated/GeneratedFrame42Widget1.dart';
import 'package:flutterapp/sigmakediapp/generatedframe43widget1/generated/GeneratedGroup85Widget1.dart';

/* Frame Frame 43
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame43Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 781.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 65.0,
              child: GeneratedFrame42Widget1(),
            ),
            Positioned(
              left: 122.0,
              top: 86.0,
              right: null,
              bottom: null,
              width: 121.0,
              height: 40.0,
              child: GeneratedlanlarmWidget(),
            ),
            Positioned(
              left: 19.5,
              top: 142.0,
              right: null,
              bottom: null,
              width: 321.0,
              height: 639.0,
              child: GeneratedGroup85Widget1(),
            )
          ]),
    ));
  }
}
