import 'package:flutter/material.dart';
import 'package:flutterapp/sigmakediapp/generatedservicecategorypagewidget/generated/GeneratedFrame43Widget.dart';

/* Frame Service Category Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedServiceCategoryPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 850.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 777.0,
                child: GeneratedFrame43Widget(),
              )
            ]),
      ),
    ));
  }
}
