import 'package:flutter/material.dart';
import 'package:flutterapp/sigmakediapp/generatedloginpagewidget/generated/GeneratedFrame96Widget.dart';

/* Frame Log-in Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 358.0,
      height: 770.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 358.0,
              height: 770.0,
              child: GeneratedFrame96Widget(),
            )
          ]),
    ));
  }
}
